name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Apple Silicon (M1/M2/M3 等)
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
            args: '--target aarch64-apple-darwin'
            arch: 'arm64'
          
          # macOS Intel
          - platform: 'macos-13'
            target: 'x86_64-apple-darwin'
            args: '--target x86_64-apple-darwin'
            arch: 'x64'
          
          # Windows x86-64
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            args: '--target x86_64-pc-windows-msvc'
            arch: 'x64'
          
          # Windows ARM64
          - platform: 'windows-latest'
            target: 'aarch64-pc-windows-msvc'
            args: '--target aarch64-pc-windows-msvc'
            arch: 'arm64'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          npm install

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          tagName: ${{ github.ref_name }}
          releaseName: '地名助手 ${{ github.ref_name }}'
          releaseBody: |
            ## 下载

            请根据您的操作系统和芯片架构选择合适的安装包：

            ### macOS
            - **Apple Silicon (M1/M2/M3 等)**: `*_aarch64.dmg`
            - **Intel 芯片**: `*_x64.dmg`

            ### Windows
            - **x86-64 (64位)**: `*_x64-setup.exe` 或 `*_x64.msi`
            - **ARM64**: `*_arm64-setup.exe` 或 `*_arm64.msi`

            ## 更新内容

            请查看 [Changelog](https://github.com/${{ github.repository }}/blob/main/README.md#-更新日志-changelog)

            ---

            基于复旦大学中国历史地名在线服务系统 API 开发
          releaseDraft: true
          prerelease: false
